[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "1.3.1"
openssl = "0.10.41"
serde = { version = "1.0.140", features = ["derive"] }
toml = "0.5.9"
